model:
  _target_: sentence_transformers.SentenceTransformer
  model_name_or_path: intfloat/multilingual-e5-small
  prompts:
    query: "query: "
  default_prompt_name: query
  
loss:
  _target_: sentence_transformers.losses.MultipleNegativesRankingLoss

evaluator:
  _target_: utils.evaluators.MappingEvaluator
  compute_metrics_fn:
    _target_: utils.evaluators.compute_precision_recall_f_beta_score
    beta: 0.5

args:
  _target_: sentence_transformers.SentenceTransformerTrainingArguments
  do_train: True
  num_train_epochs: 3
  eval_strategy: epoch
  save_strategy: epoch
  per_device_train_batch_size: 256
  learning_rate: 2E-04
  seed: 21
  warmup_steps: 20
  save_total_limit: 1
  metric_for_best_model: "f_score"
